before_script:
  - apt update
  - DEBIAN_FRONTEND=noninteractive apt install -yq build-essential cmake git

build:ubuntu:20.04:
  stage: build
  image: ubuntu:20.04
  artifacts:
    paths:
       - "build/ydotool"
       - "build/ydotoold"
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make
